using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using System.Net.Mail;
using System.Configuration;

namespace  Mango.Business
{
    public class EmailLogic
    {
        //private const string MAIL_MESSAGE_FROM_SUPERVISOR_APPRAISEE = "You have been appraised by your supervisor ( Joy Omasan ). Go and complete your appraisal at http://csl-netapp/appraisalSystem";
        //private const string MAIL_MESSAGE_FROM_APPRAISEE_TO_HOD = "Appraisee ( Akeem Kazeem ) has accepted his appraisal. Please login to Appraisal System at http://csl-netapp/appraisalSystem to complete the appraisal.";
        //private const string MAIL_MESSAGE_FROM_APPRAISEE_TO_SUPERVISOR = "";

        public EmailLogic() { }
        public EmailLogic(string name, string emailAddress, string phone, string comment)
        {
            Name = name;
            EmailAddress = emailAddress;
            Phone = phone;
            Comment = comment;
        }

        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        public string Comment { get; set; }

        //public bool SendSimpleMail()
        public bool Send()
        {
            string body = "<html><head></head><body>";
            body += "<h1>" + "Request.Path" + "</h1>";
            body += "<h2>" + DateTime.Now + "</h2>";
            body += "Server.GetLastError().ToString()";
            body += "</body></html>";

            // Construct the mail message
            MailMessage mail = new MailMessage();

            mail.To.Add(new MailAddress("administrator@dan"));
            mail.From = new MailAddress("autogenerated@buggysoftware.com");
            mail.Subject = "Critical Application Exception";
            mail.IsBodyHtml = true;
            mail.Body = body;

            // Send the email
            SmtpClient mailer = new SmtpClient();
            mailer.Host = "localhost";

            try
            {
                mailer.Send(mail);
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public bool Send(DateTime mailDate, string addressee, string salutation, string mailTitle, string mailBody, string nameFrom, string subject, string phone, string mailTo)
        {
            try
            {
                string smtpServer = ConfigurationManager.AppSettings["SmtpServer"];
                string adminEmail = ConfigurationManager.AppSettings["adminEmail"];

                string msg = "";
                MailMessage message = new MailMessage();
                
                //constant variable declaration
                const string DIV = "<DIV>";
                const string END_DIV = "</DIV>";
                const string PARAG = "<P>";
                const string END_PARAG = "</P>";
                const string NEW_LINE = "<BR>";
                const string BOLD = "<B>";
                const string END_BOLD = "</B>";
                const string FONT_FACE = "<FONT FACE = ";
                const string END_FONT = "</FONT>";
                const string FONT_SIZE = "<FONT SIZE = ";

                //build font face for the mail
                msg = FONT_SIZE + 2;

                //msg = FONT_FACE & "'Verdana'"
                msg += FONT_FACE + "'Tahoma'";

                //build date part of the mail
                msg += DIV + mailDate + END_DIV;

                //build the address of the addressee mail part
                msg += DIV + PARAG + addressee + END_PARAG + END_DIV;

                //build the address of the addressee phone part
                msg += DIV + PARAG + phone + END_PARAG + END_DIV + NEW_LINE;

                //build salutation mail part
                msg += DIV + salutation + END_DIV + NEW_LINE;

                //build mail title part
                if (mailTitle != null)
                {
                    msg += DIV + BOLD + mailTitle + END_BOLD + END_DIV;
                }

                //build body of the mail
                msg += DIV + mailBody + END_DIV;

                //build mail closing part
                //msg += DIV + PARAG + "Thank you," + NEW_LINE + "Yours Faithfully" + END_PARAG;
                msg += DIV + PARAG + NEW_LINE + "Regards," + NEW_LINE + END_PARAG;
                msg += PARAG + nameFrom + END_PARAG + END_DIV;

                //end font face
                msg += END_FONT;
                msg += END_FONT;

                //build email message with the information gathered
                //message.Cc = adminEmail;
                message.IsBodyHtml = true;
                message.To.Add(new MailAddress(mailTo));
                message.From = new MailAddress(adminEmail);
                message.Priority = MailPriority.High;
                message.Subject = subject;
                message.Body = msg;
                
                // Send the email
                SmtpClient mailer = new SmtpClient();
                mailer.Host = smtpServer;
                mailer.Send(message);

                return true;
            }
            catch (Exception)
            {
                throw;
            }
        }





    }
}
